<?php

namespace infotech\components\models;

use ReflectionClass;

class Company
{
    public const FORM_OOO = 'ООО';
    public const FORM_AO = 'АО';
    public const FORM_OAO = 'ОАО';
    public const FORM_TOO = 'ТОО';
    public const FORM_IB = 'ИП';
    public const FORM_ZAO = 'ЗАО';
    public const FORM_COOO = 'СООО';
    public const FORM_ODO = 'ОДО';
    public const FORM_CHUP = 'ЧУП';
    public const FORM_CHTUP = 'ЧТУП';
    public const FORM_CHPTUP = 'ЧПТУП';
    public const FORM_FH = 'ФХ';
    public const FORM_PAO = 'ПАО';
    public const FORM_GBY = 'ГБУ';
    public const FORM_CPOK = 'СПОК';
    public const FORM_MOY = 'МОУ';
    public const FORM_FKP = 'ФКП';
    public const FORM_MYYP = 'МУУП';
    public const FORM_DYP = 'ДУП';
    public const FORM_DP = 'ДП';
    public const FORM_PK = 'ПК';
    public const FORM_ART = 'Арт';
    public const FORM_CXK = 'СХК';
    public const FORM_PT = 'ПТ';
    public const FORM_TV = 'ТВ';
    public const FORM_FL = 'ФЛ';
    public const FORM_PRED = 'ПРЕД';
    public const FORM_OO = 'OO'; //https://zakonbase.ru/content/part/291477?print=1
    public const FORM_RO = 'РО';
    public const FORM_F = 'Ф';
    public const FORM_KFX = 'КФХ';
    public const FORM_FGUP = 'ФГУП';
    public const FORM_CHPK = 'СХПК';
    public const FORM_KH = 'KX';
    public const FORM_GKFX = 'ГКФХ';
    public const FORM_FCVNG_RF = 'ФСВНГ РФ';
    public const FORM_FKU = 'ФКУ';
    public const FORM_FKGU = 'ФКГУ';
    public const FORM_SPSSPK = 'СПССПК';
    public const FORM_UFSIN = 'УФСИН';
    public const FORM_NAO = 'НАО';
    public const FORM_ANO = 'АНО';
    public const FORM_SPAO = 'СПАО';
    public const FORM_ASSOC = 'Ассоциация';
    public const FORM_CHU = 'ЧУ'; // Частное учреждение; код ОКОПФ: 75500.
    public const FORM_NOCHU = 'НОЧУ';
    public const FORM_GUP = 'ГУП';
    public const FORM_OOB = 'ООБ';
    public const FORM_ROB = 'РОБ';
    public const FORM_CHURCH = 'Церковь';
    public const FORM_COMING = 'Приход';
    public const FORM_COMMUNITY = 'Община';
    public const FORM_MONASTERY = 'Монастырь';
    public const FORM_MISSION = 'Миссия';
    public const FORM_FOND = 'Фонд';
    public const FORM_NP = 'НП';
    public const FORM_UCH = 'Уч';
    public const FORM_GUCH = 'ГУЧ';
    public const FORM_MUCH = 'МУЧ';
    public const FORM_OUCH = 'ОУЧ';
    public const FORM_UNION = 'Союз';
    public const FORM_TSZH = 'ТСЖ';
    public const FORM_CNDMNM = 'Кондоминиум';
    public const FORM_PTK = 'ПТК';
    public const FORM_OD = 'ОД';
    public const FORM_OF = 'ОФ';
    public const FORM_OOS = 'ООС';
    public const FORM_DOUC = 'ДОУч';
    public const FORM_OPROF = 'Опроф';
    public const FORM_TOPROF = 'ТОПроф';
    public const FORM_PPO = 'ППО';
    public const FORM_PARTY = 'Партия';
    public const FORM_AOZT = 'АОЗТ';
    public const FORM_AOOT = 'АООТ';
    public const FORM_MP = 'МП';
    public const FORM_ICHP = 'ИЧП';
    public const FORM_SEM = 'СЕМ';
    public const FORM_SP = 'СП';
    public const FORM_GP = 'ГП';
    public const FORM_MUP = 'МУП';
    public const FORM_POO = 'ПОО';
    public const FORM_PPKOOP = 'ППКООП';
    public const FORM_UOO = 'УОО';
    public const FORM_UCHPTK = 'УЧПТК';
    public const FORM_KOMBANK = 'Комбанк';
    public const FORM_SMT = 'СМТ';
    public const FORM_ST = 'СТ';
    public const FORM_KLH = 'КЛХ';
    public const FORM_SVH = 'СВХ';
    public const FORM_ZHSK = 'ЖСК';
    public const FORM_GSK = 'ГСК';
    public const FORM_FIRM = 'Фирма';
    public const FORM_NPO = 'НПО';
    public const FORM_PO = 'ПО';
    public const FORM_SKB = 'СКБ';
    public const FORM_KB = 'КБ';
    public const FORM_UPTK = 'УПТК';
    public const FORM_SMU = 'СМУ';
    public const FORM_HOZU = 'ХОЗУ';
    public const FORM_NTC = 'НТЦ';
    public const FORM_FIK = 'ФИК';
    public const FORM_NPP = 'НПП';
    public const FORM_CHIF = 'ЧИФ';
    public const FORM_CHOP = 'ЧОП';
    public const FORM_REU = 'РЭУ';
    public const FORM_PIF = 'ПИФ';
    public const FORM_GKOOP = 'ГКООП';
    public const FORM_POB = 'ПОБ';
    public const FORM_PS = 'ПС';
    public const FORM_KS = 'КС';
    public const FORM_FF = 'ФФ';
    public const FORM_FPG = 'ФПГ';
    public const FORM_MHP = 'МХП';
    public const FORM_LPH = 'ЛПХ';
    public const FORM_AP = 'АП';
    public const FORM_OP = 'ОП';
    public const FORM_NPF = 'НПФ';
    public const FORM_PKF = 'ПКФ';
    public const FORM_PKP = 'ПКП';
    public const FORM_PKK = 'ПКК';
    public const FORM_KF = 'КФ';
    public const FORM_TF = 'ТФ';
    public const FORM_TD = 'ТД';
    public const FORM_DSU = 'Д(С)У';
    public const FORM_TFPG = 'ТФПГ';
    public const FORM_MFPG = 'МФПГ';
    public const FORM_DS = 'Д/С';
    public const FORM_BCA = 'Б-ца';
    public const FORM_PKA = 'П-ка';
    public const FORM_AKA = 'А-ка';
    public const FORM_ZD = 'З-д';
    public const FORM_ADOK = 'АДОК';
    public const FORM_REDSMI = 'РедСМИ';
    public const FORM_PRT = 'ПрТ';
    public const FORM_APAOOT = 'АПАООТ';
    public const FORM_OPAOOT = 'ОПАООТ';
    public const FORM_OPAOZT = 'ОПАОЗТ';
    public const FORM_OPTOO = 'ОПТОО';
    public const FORM_APAOZT = 'АПАОЗТ';
    public const FORM_APTOO = 'АПТОО';
    public const FORM_APST = 'АПСТ';
    public const FORM_APPT = 'АППТ';
    public const FORM_OPST = 'ОПСТ';
    public const FORM_OPPT = 'ОППТ';
    public const FORM_ASKFH = 'АСКФХ';
    public const FORM_SOYUZKFH = 'СОЮЗКФХ';
    public const FORM_SOYUZPOB = 'СОЮЗПОБ';
    public const FORM_SCHOOL = 'Школа';
    public const FORM_INT = 'Ин-т';
    public const FORM_RSU = 'РСУ';
    public const FORM_CORP = 'Корп';
    public const FORM_COMP = 'Комп';
    public const FORM_BKA = 'Б-ка';
    public const FORM_BSP = 'БСП';
    public const FORM_CRB = 'ЦРБ';
    public const FORM_MUUCH = 'МУУЧ';
    public const FORM_MSCH = 'МСЧ';
    public const FORM_CRBUH = 'ЦРБУХ';
    public const FORM_CBUH = 'ЦБУХ';
    public const FORM_FNDL = 'ФИНОТДЕЛ';
    public const FORM_KC = 'КЦ';
    public const FORM_PROFKOM = 'ПРОФКОМ';
    public const FORM_ATP = 'АТП';
    public const FORM_PATP = 'ПАТП';
    public const FORM_CDN = 'ЦДН';
    public const FORM_NOTP = 'НОТП';
    public const FORM_NOTK = 'НОТК';
    public const FORM_YAS = 'Я/С';
    public const FORM_OTD = 'ОТД';
    public const FORM_ZHD = 'ЖД';
    public const FORM_KOOP = 'КООП';
    public const FORM_BU = 'БУ';
    public const FORM_SAU = 'САУ';
    public const FORM_KU = 'КУ';
    public const FORM_AOOO = 'ПРЕДСТАВИТЕЛЬСТВО АООО';
    public const FORM_FGAU = 'ФГАУ'; // Федеральное государственное автономное учреждение; код ОКОПФ: 75101.
    public const FORM_FGBU = 'ФГБУ'; // Федеральное государственное бюджетное учреждение; код ОКОПФ: 75103.
    public const FORM_FGKU = 'ФГКУ'; // Федеральное государственное казенное учреждение; код ОКОПФ: 75104.
    public const FORM_FBUZ = 'ФБУЗ'; // Федеральное бюджетное учреждение здравоохранения
    public const FORM_SPK = 'СПК';

    public const FORM_GAU = 'ГАУ';

    public static function getLegalFormList(): array
    {
        $reflection = new ReflectionClass(self::class);
        $forms = array_values($reflection->getConstants());

        return array_combine($forms, $forms);
    }
}
