<?php

namespace infotech\components\models;

class Company
{
    public const FORM_OOO = 'ООО';
    public const FORM_AO = 'АО';
    public const FORM_OAO = 'ОАО';
    public const FORM_TOO = 'ТОО';
    public const FORM_IB = 'ИП';
    public const FORM_ZAO = 'ЗАО';
    public const FORM_COOO = 'СООО';
    public const FORM_ODO = 'ОДО';
    public const FORM_CHUP = 'ЧУП';
    public const FORM_CHTUP = 'ЧТУП';
    public const FORM_CHPTUP = 'ЧПТУП';
    public const FORM_FH = 'ФХ';
    public const FORM_PAO = 'ПАО';
    public const FORM_GBY = 'ГБУ';
    public const FORM_CPOK = 'СПОК';
    public const FORM_MOY = 'МОУ';
    public const FORM_FKP = 'ФКП';
    public const FORM_MYYP = 'МУУП';
    public const FORM_DYP = 'ДУП';
    public const FORM_DP = 'ДП';
    public const FORM_PK = 'ПК';
    public const FORM_ART = 'Арт';
    public const FORM_CXK = 'СХК';
    public const FORM_PT = 'ПТ';
    public const FORM_TV = 'ТВ';
    public const FORM_FL = 'ФЛ';
    public const FORM_PRED = 'ПРЕД';
    public const FORM_OO = 'OO'; //https://zakonbase.ru/content/part/291477?print=1
    public const FORM_RO = 'РО';
    public const FORM_F = 'Ф';
    public const FORM_KFX = 'КФХ';
    public const FORM_FGUP = 'ФГУП';
    public const FORM_CHPK = 'СХПК';
    public const FORM_KH = 'KX';
    public const FORM_GKFX = 'ГКФХ';
    public const FORM_FCVNG_RF = 'ФСВНГ РФ';
    public const FORM_FKU = 'ФКУ';
    public const FORM_FKGU = 'ФКГУ';
    public const FORM_SPSSPK = 'СПССПК';
    public const FORM_UFSIN = 'УФСИН';
    public const FORM_NAO = 'НАО';
    public const FORM_ANO = 'АНО';
    public const FORM_SPAO = 'СПАО';
    public const FORM_ASSOC = 'Ассоциация';
    public const FORM_CHU = 'ЧУ'; // Частное учреждение, код ОКОПФ: 75500.
    public const FORM_NOCHU = 'НОЧУ';
    public const FORM_GUP = 'ГУП';
    public const FORM_OOB = 'ООБ';
    public const FORM_ROB = 'РОБ';
    public const FORM_CHURCH = 'Церковь';
    public const FORM_COMING = 'Приход';
    public const FORM_COMMUNITY = 'Община';
    public const FORM_MONASTERY = 'Монастырь';
    public const FORM_MISSION = 'Миссия';
    public const FORM_FOND = 'Фонд';
    public const FORM_NP = 'НП';
    public const FORM_UCH = 'Уч';
    public const FORM_GUCH = 'ГУЧ';
    public const FORM_MUCH = 'МУЧ';
    public const FORM_OUCH = 'ОУЧ';
    public const FORM_UNION = 'Союз';
    public const FORM_TSZH = 'ТСЖ';
    public const FORM_CNDMNM = 'Кондоминиум';
    public const FORM_PTK = 'ПТК';
    public const FORM_OD = 'ОД';
    public const FORM_OF = 'ОФ';
    public const FORM_OOS = 'ООС';
    public const FORM_DOUC = 'ДОУч';
    public const FORM_OPROF = 'Опроф';
    public const FORM_TOPROF = 'ТОПроф';
    public const FORM_PPO = 'ППО';
    public const FORM_PARTY = 'Партия';
    public const FORM_AOZT = 'АОЗТ';
    public const FORM_AOOT = 'АООТ';
    public const FORM_MP = 'МП';
    public const FORM_ICHP = 'ИЧП';
    public const FORM_SEM = 'СЕМ';
    public const FORM_SP = 'СП';
    public const FORM_GP = 'ГП';
    public const FORM_MUP = 'МУП';
    public const FORM_POO = 'ПОО';
    public const FORM_PPKOOP = 'ППКООП';
    public const FORM_UOO = 'УОО';
    public const FORM_UCHPTK = 'УЧПТК';
    public const FORM_KOMBANK = 'Комбанк';
    public const FORM_SMT = 'СМТ';
    public const FORM_ST = 'СТ';
    public const FORM_KLH = 'КЛХ';
    public const FORM_SVH = 'СВХ';
    public const FORM_ZHSK = 'ЖСК';
    public const FORM_GSK = 'ГСК';
    public const FORM_FIRM = 'Фирма';
    public const FORM_NPO = 'НПО';
    public const FORM_PO = 'ПО';
    public const FORM_SKB = 'СКБ';
    public const FORM_KB = 'КБ';
    public const FORM_UPTK = 'УПТК';
    public const FORM_SMU = 'СМУ';
    public const FORM_HOZU = 'ХОЗУ';
    public const FORM_NTC = 'НТЦ';
    public const FORM_FIK = 'ФИК';
    public const FORM_NPP = 'НПП';
    public const FORM_CHIF = 'ЧИФ';
    public const FORM_CHOP = 'ЧОП';
    public const FORM_REU = 'РЭУ';
    public const FORM_PIF = 'ПИФ';
    public const FORM_GKOOP = 'ГКООП';
    public const FORM_POB = 'ПОБ';
    public const FORM_PS = 'ПС';
    public const FORM_KS = 'КС';
    public const FORM_FF = 'ФФ';
    public const FORM_FPG = 'ФПГ';
    public const FORM_MHP = 'МХП';
    public const FORM_LPH = 'ЛПХ';
    public const FORM_AP = 'АП';
    public const FORM_OP = 'ОП';
    public const FORM_NPF = 'НПФ';
    public const FORM_PKF = 'ПКФ';
    public const FORM_PKP = 'ПКП';
    public const FORM_PKK = 'ПКК';
    public const FORM_KF = 'КФ';
    public const FORM_TF = 'ТФ';
    public const FORM_TD = 'ТД';
    public const FORM_DSU = 'Д(С)У';
    public const FORM_TFPG = 'ТФПГ';
    public const FORM_MFPG = 'МФПГ';
    public const FORM_DS = 'Д/С';
    public const FORM_BCA = 'Б-ца';
    public const FORM_PKA = 'П-ка';
    public const FORM_AKA = 'А-ка';
    public const FORM_ZD = 'З-д';
    public const FORM_ADOK = 'АДОК';
    public const FORM_REDSMI = 'РедСМИ';
    public const FORM_PRT = 'ПрТ';
    public const FORM_APAOOT = 'АПАООТ';
    public const FORM_APAOZT = 'АПАОЗТ';
    public const FORM_APTOO = 'АПТОО';
    public const FORM_APST = 'АПСТ';
    public const FORM_APPT = 'АППТ';
    public const FORM_OPST = 'ОПСТ';
    public const FORM_OPPT = 'ОППТ';
    public const FORM_ASKFH = 'АСКФХ';
    public const FORM_SOYUZKFH = 'СОЮЗКФХ';
    public const FORM_SOYUZPOB = 'СОЮЗПОБ';
    public const FORM_SCHOOL = 'Школа';
    public const FORM_INT = 'Ин-т';
    public const FORM_RSU = 'РСУ';
    public const FORM_CORP = 'Корп';
    public const FORM_COMP = 'Комп';
    public const FORM_BKA = 'Б-ка';
    public const FORM_BSP = 'БСП';
    public const FORM_CRB = 'ЦРБ';
    public const FORM_MUUCH = 'МУУЧ';
    public const FORM_MSCH = 'МСЧ';
    public const FORM_CRBUH = 'ЦРБУХ';
    public const FORM_CBUH = 'ЦБУХ';
    public const FORM_FNDL = 'ФИНОТДЕЛ';
    public const FORM_KC = 'КЦ';
    public const FORM_PROFKOM = 'ПРОФКОМ';
    public const FORM_ATP = 'АТП';
    public const FORM_PATP = 'ПАТП';
    public const FORM_CDN = 'ЦДН';
    public const FORM_NOTP = 'НОТП';
    public const FORM_NOTK = 'НОТК';
    public const FORM_YAS = 'Я/С';
    public const FORM_OTD = 'ОТД';
    public const FORM_ZHD = 'ЖД';
    public const FORM_KOOP = 'КООП';
    public const FORM_BU = 'БУ';
    public const FORM_SAU = 'САУ';
    public const FORM_KU = 'КУ';

    public static function getLegalFormList(): array
    {
        return [
            self::FORM_OOO => self::FORM_OOO,
            self::FORM_AO => self::FORM_AO,
            self::FORM_OAO => self::FORM_OAO,
            self::FORM_TOO => self::FORM_TOO,
            self::FORM_IB => self::FORM_IB,
            self::FORM_ZAO => self::FORM_ZAO,
            self::FORM_COOO => self::FORM_COOO,
            self::FORM_ODO => self::FORM_ODO,
            self::FORM_CHUP => self::FORM_CHUP,
            self::FORM_CHTUP => self::FORM_CHTUP,
            self::FORM_CHPTUP => self::FORM_CHPTUP,
            self::FORM_FH => self::FORM_FH,
            self::FORM_PAO => self::FORM_PAO,
            self::FORM_GBY => self::FORM_GBY,
            self::FORM_CPOK => self::FORM_CPOK,
            self::FORM_MOY => self::FORM_MOY,
            self::FORM_FKP => self::FORM_FKP,
            self::FORM_MYYP => self::FORM_MYYP,
            self::FORM_DYP => self::FORM_DYP,
            self::FORM_DP => self::FORM_DP,
            self::FORM_PK => self::FORM_PK,
            self::FORM_ART => self::FORM_ART,
            self::FORM_CXK => self::FORM_CXK,
            self::FORM_PT => self::FORM_PT,
            self::FORM_TV => self::FORM_TV,
            self::FORM_FL => self::FORM_FL,
            self::FORM_PRED => self::FORM_PRED,
            self::FORM_OO => self::FORM_OO, // https://zakonbase.ru/content/part/291477?print=1
            self::FORM_RO => self::FORM_RO,
            self::FORM_F => self::FORM_F,
            self::FORM_KFX => self::FORM_KFX,
            self::FORM_FGUP => self::FORM_FGUP,
            self::FORM_CHPK => self::FORM_CHPK,
            self::FORM_KH => self::FORM_KH,
            self::FORM_GKFX => self::FORM_GKFX,
            self::FORM_FCVNG_RF => self::FORM_FCVNG_RF,
            self::FORM_FKU => self::FORM_FKU,
            self::FORM_FKGU => self::FORM_FKGU,
            self::FORM_SPSSPK => self::FORM_SPSSPK,
            self::FORM_UFSIN => self::FORM_UFSIN,
            self::FORM_NAO => self::FORM_NAO,
            self::FORM_ANO => self::FORM_ANO,
            self::FORM_SPAO => self::FORM_SPAO,
            self::FORM_ASSOC => self::FORM_ASSOC,
            self::FORM_CHU => self::FORM_CHU,
            self::FORM_NOCHU => self::FORM_NOCHU,
            self::FORM_GUP => self::FORM_GUP,
            self::FORM_OOB => self::FORM_OOB,
            self::FORM_ROB => self::FORM_ROB,
            self::FORM_CHURCH => self::FORM_CHURCH,
            self::FORM_COMING => self::FORM_COMING,
            self::FORM_COMMUNITY => self::FORM_COMMUNITY,
            self::FORM_MONASTERY => self::FORM_MONASTERY,
            self::FORM_MISSION => self::FORM_MISSION,
            self::FORM_NP => self::FORM_NP,
            self::FORM_UCH => self::FORM_UCH,
            self::FORM_GUCH => self::FORM_GUCH,
            self::FORM_MUCH => self::FORM_MUCH,
            self::FORM_OUCH => self::FORM_OUCH,
            self::FORM_UNION => self::FORM_UNION,
            self::FORM_TSZH => self::FORM_TSZH,
            self::FORM_CNDMNM => self::FORM_CNDMNM,
            self::FORM_PTK => self::FORM_PTK,
            self::FORM_OD => self::FORM_OD,
            self::FORM_OF => self::FORM_OF,
            self::FORM_OOS => self::FORM_OOS,
            self::FORM_DOUC => self::FORM_DOUC,
            self::FORM_OPROF => self::FORM_OPROF,
            self::FORM_TOPROF => self::FORM_TOPROF,
            self::FORM_PPO => self::FORM_PPO,
            self::FORM_PARTY => self::FORM_PARTY,
            self::FORM_AOZT => self::FORM_AOZT,
            self::FORM_AOOT => self::FORM_AOOT,
            self::FORM_MP => self::FORM_MP,
            self::FORM_ICHP => self::FORM_ICHP,
            self::FORM_SEM => self::FORM_SEM,
            self::FORM_SP => self::FORM_SP,
            self::FORM_GP => self::FORM_GP,
            self::FORM_MUP => self::FORM_MUP,
            self::FORM_POO => self::FORM_POO,
            self::FORM_PPKOOP => self::FORM_PPKOOP,
            self::FORM_UOO => self::FORM_UOO,
            self::FORM_UCHPTK => self::FORM_UCHPTK,
            self::FORM_KOMBANK => self::FORM_KOMBANK,
            self::FORM_SMT => self::FORM_SMT,
            self::FORM_ST => self::FORM_ST,
            self::FORM_KLH => self::FORM_KLH,
            self::FORM_SVH => self::FORM_SVH,
            self::FORM_ZHSK => self::FORM_ZHSK,
            self::FORM_GSK => self::FORM_GSK,
            self::FORM_FIRM => self::FORM_FIRM,
            self::FORM_NPO => self::FORM_NPO,
            self::FORM_KB => self::FORM_KB,
            self::FORM_SKB => self::FORM_SKB,
            self::FORM_UPTK => self::FORM_UPTK,
            self::FORM_SMU => self::FORM_SMU,
            self::FORM_HOZU => self::FORM_HOZU,
            self::FORM_NTC => self::FORM_NTC,
            self::FORM_FIK => self::FORM_FIK,
            self::FORM_NPP => self::FORM_NPP,
            self::FORM_CHIF => self::FORM_CHIF,
            self::FORM_CHOP => self::FORM_CHOP,
            self::FORM_REU => self::FORM_REU,
            self::FORM_PIF => self::FORM_PIF,
            self::FORM_GKOOP => self::FORM_GKOOP,
            self::FORM_POB => self::FORM_POB,
            self::FORM_PS => self::FORM_PS,
            self::FORM_KS => self::FORM_KS,
            self::FORM_FF => self::FORM_FF,
            self::FORM_FPG => self::FORM_FPG,
            self::FORM_MHP => self::FORM_MHP,
            self::FORM_LPH => self::FORM_LPH,
            self::FORM_AP => self::FORM_AP,
            self::FORM_OP => self::FORM_OP,
            self::FORM_NPF => self::FORM_NPF,
            self::FORM_PKF => self::FORM_PKF,
            self::FORM_PKP => self::FORM_PKP,
            self::FORM_PKK => self::FORM_PKK,
            self::FORM_KF => self::FORM_KF,
            self::FORM_TF => self::FORM_TF,
            self::FORM_TD => self::FORM_TD,
            self::FORM_DSU => self::FORM_DSU,
            self::FORM_TFPG => self::FORM_TFPG,
            self::FORM_MFPG => self::FORM_MFPG,
            self::FORM_DS => self::FORM_DS,
            self::FORM_BCA => self::FORM_BCA,
            self::FORM_PKA => self::FORM_PKA,
            self::FORM_AKA => self::FORM_AKA,
            self::FORM_ZD => self::FORM_ZD,
            self::FORM_ADOK => self::FORM_ADOK,
            self::FORM_REDSMI => self::FORM_REDSMI,
            self::FORM_PRT => self::FORM_PRT,
            self::FORM_APAOOT => self::FORM_APAOOT,
            self::FORM_APAOZT => self::FORM_APAOZT,
            self::FORM_APTOO => self::FORM_APTOO,
            self::FORM_APST => self::FORM_APST,
            self::FORM_APPT => self::FORM_APPT,
            self::FORM_OPST => self::FORM_OPST,
            self::FORM_OPPT => self::FORM_OPPT,
            self::FORM_ASKFH => self::FORM_ASKFH,
            self::FORM_SOYUZKFH => self::FORM_SOYUZKFH,
            self::FORM_SOYUZPOB => self::FORM_SOYUZPOB,
            self::FORM_SCHOOL => self::FORM_SCHOOL,
            self::FORM_INT => self::FORM_INT,
            self::FORM_RSU => self::FORM_RSU,
            self::FORM_CORP => self::FORM_CORP,
            self::FORM_COMP => self::FORM_COMP,
            self::FORM_BKA => self::FORM_BKA,
            self::FORM_BSP => self::FORM_BSP,
            self::FORM_CRB => self::FORM_CRB,
            self::FORM_MUUCH => self::FORM_MUUCH,
            self::FORM_MSCH => self::FORM_MSCH,
            self::FORM_CRBUH => self::FORM_CRBUH,
            self::FORM_CBUH => self::FORM_CBUH,
            self::FORM_FNDL => self::FORM_FNDL,
            self::FORM_KC => self::FORM_KC,
            self::FORM_PROFKOM => self::FORM_PROFKOM,
            self::FORM_ATP => self::FORM_ATP,
            self::FORM_PATP => self::FORM_PATP,
            self::FORM_CDN => self::FORM_CDN,
            self::FORM_NOTP => self::FORM_NOTP,
            self::FORM_NOTK => self::FORM_NOTK,
            self::FORM_YAS => self::FORM_YAS,
            self::FORM_OTD => self::FORM_OTD,
            self::FORM_ZHD => self::FORM_ZHD,
            self::FORM_KOOP => self::FORM_KOOP,
            self::FORM_BU => self::FORM_BU,
            self::FORM_SAU => self::FORM_SAU,
            self::FORM_KU => self::FORM_KU,
            self::FORM_PO => self::FORM_PO,
        ];
    }
}